theme: minima
url: "https://sedelmeyer.github.io/predicting-crime/"
repository: "https://github.com/sedelmeyer/predicting-crime"

header_pages:
 - pages/about.md
 - pages/data.md
 - pages/models.md
 - pages/results.md